/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://example.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_cloud_logic_custom": [
        {
            "name": "api",
            "endpoint": "https://example.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ]
};

export default awsmobile;

